[build-system]
requires = []
build-backend = "madrona-py-build"
backend-path = ["external/py"]

[project]
name = "mad_trade"
version = "0.0.1"

[tool.madrona.packages.mad_trade]
ext-only = true
ext-out-dir = "build"
